### ISSUE TITLE
hello!

### ISSUE THREAD

**Issue by Eduard123321** [mrhenrike/MikrotikAPI-BF#8]
python3 ~/MikrotikAPI-BF/mikrotikapi-bf.py -t 127.0.0.1 -p 505 -u admin -d /home/kali/SecLists/Passwords/500-worst-passwords.txt -s 5
/home/kali/MikrotikAPI-BF/mikrotikapi-bf.py:42: SyntaxWarning: invalid escape sequence '\/'
  banner=('''

        __  __ _ _              _   _ _        _    ____ ___      ____  _____
        |  \/  (_) | ___ __ ___ | |_(_) | __   / \  |  _ \_ _|    | __ )|  ___|
        | |\/| | | |/ / '__/ _ \| __| | |/ /  / _ \ | |_) | |_____|  _ \| |_
        | |  | | |   <| | | (_) | |_| |   <  / ___ \|  __/| |_____| |_) |  _|
        |_|  |_|_|_|\_\_|  \___/ \__|_|_|\_\/_/   \_\_|  |___|    |____/|_|

                    Mikrotik RouterOS API Bruteforce Tool 1.1
                            André Henrique (@mrhenrike)
          Please report tips, suggests and problems to Twitter (@mrhenrike)
                    https://github.com/mrhenrike/MikrotikAPI-BF
       
[*] Starting bruteforce attack...
---------------------------------
[-] SOCKET ERROR! Check Target (IP or PORT parameters). Exiting...
Traceback (most recent call last):
  File "/home/kali/MikrotikAPI-BF/mikrotikapi-bf.py", line 138, in open_socket
    self.connection = self.sock.connect(sa)
                      ^^^^^^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/MikrotikAPI-BF/mikrotikapi-bf.py", line 497, in <module>
    main()
  File "/home/kali/MikrotikAPI-BF/mikrotikapi-bf.py", line 452, in main
    apiros = ApiRos(s, target, "admin", "", port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/MikrotikAPI-BF/mikrotikapi-bf.py", line 122, in __init__
    self.create_connection()
  File "/home/kali/MikrotikAPI-BF/mikrotikapi-bf.py", line 342, in create_connection
    self.open_socket()
  File "/home/kali/MikrotikAPI-BF/mikrotikapi-bf.py", line 147, in open_socket
    raise CreateSocketError('Error: API failed to connect to socket. Host: {}, port: {}.'.format(self.target, self.port))
CreateSocketError: Error: API failed to connect to socket. Host: 127.0.0.1, port: 8728.

**Comment by mxmandr** [comment]
You can bruteforce only the API port, which is 8728 by default. The web or winbox port cannot be bruteforced. The -p key does not work.

**Comment by mrhenrike** [comment]
## What went wrong in your log

1. **Port:** RouterOS **API** listens on **8728** by default (unless you changed it on the router). In current releases use \--api-port 8728\ (default). The traceback shows the client trying **8728** while your command used \-p 505\ — in **v3.x**, \-p\ is **\--passlist\** (password file), **not** the API port, so \505\ was interpreted as a wordlist path, not a TCP port.
2. **Connection refused:** \127.0.0.1:8728\ means **nothing is accepting API connections** on your machine (no RouterOS, API disabled, or wrong host). Point \-t\ at the **router IP** and ensure **API service** is enabled and reachable.

3. **SyntaxWarning** on the old ASCII banner: addressed in newer tree (banner / string handling cleaned up).

If anything still fails on **v3.2.0+** with \--api-port\ set correctly and API enabled on the device, open a **new** issue with \python mikrotikapi-bf.py --version\ and the exact CLI line (redact secrets).

**Comment by mrhenrike** [comment]
Closing: explained API port vs -p flag and connection refused causes; use current CLI (--api-port) and a reachable RouterOS API.
